version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.Backend
    container_name: ava_fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env  
    volumes:
      - ./data:/app/data
      - ./processing_pipeline:/app/processing_pipeline
      - ./final_Depolyement_setup:/app/final_Depolyement_setup

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.Frontend
    container_name: ava_streamlit
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - FASTAPI_URL=http://fastapi:8000
    volumes:
      - ./processing_pipeline:/app/processing_pipeline
      - ./final_Depolyement_setup:/app/final_Depolyement_setup
      - ./frontend.py:/app/frontend.py
