version: "3.9"

services:
  fastapi:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_FASTAPI}:${IMAGE_TAG}
    container_name: ava_fastapi_prod
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

  streamlit:
    image: ${ECR_REGISTRY}/${ECR_REPOSITORY_STREAMLIT}:${IMAGE_TAG}
    container_name: ava_streamlit_prod
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: unless-stopped
