FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY final_Depolyement_setup /app/final_Depolyement_setup
COPY processing_pipeline /app/processing_pipeline
COPY frontend.py /app/frontend.py
COPY .env /app/.env

EXPOSE 8501

CMD ["streamlit", "run", "final_Depolyement_setup/frontend.py", "--server.port=8501", "--server.address=0.0.0.0"]
